# metadata specialised for each experiment
core:
  project_name: thesis-gan
  storage_dir: ${oc.env:PROJECT_ROOT}/storage
  version: 0.0.1
  tags: null

defaults:
  - hydra: default
  - train: default
  - model: timegan
  - data: sines
  - _self_ # as last argument to allow the override of parameters via this main config
#    Decomment this parameter to get parallel job running
#  - hydra/launcher: joblib
