_target_: dataset.datamodule.MyDataModule
dataset_train: ${dataset.train}
dataset_val: ${dataset.val}
batch_size: ${batch_size}

pipeline_price:
  _target_: dataset.pipeline.LogReturnPipeline
  scaler:
    _target_: sklearn.preprocessing.StandardScaler

pipeline_volume:
  _target_: dataset.pipeline.ScalerPipeline
  scaler:
    _target_: sklearn.preprocessing.MinMaxScaler
    feature_range: ${as_tuple:-1,1}
  round: True
  log: True