dataset_type: "multistock"
target_feature_price: mid_price
target_feature_volume: volume
stock_names: [KO, PEP, NVDA, KSU]
encoder_length: 390
decoder_length: 150


data:
  _target_: thesis_gan.data.datamodule.MyDataModule

  dataset_type: ${nn.dataset_type}

  data_pipeline_price:
    _target_: thesis_gan.data.pipeline.LogReturnPipeline
    scaler:
      _target_: sklearn.preprocessing.StandardScaler

  data_pipeline_volume:
    _target_: thesis_gan.data.pipeline.ScalerPipeline
    scaler:
      _target_: sklearn.preprocessing.StandardScaler

  datasets:
    train:
      _target_: thesis_gan.data.dataset.StockDataset
      path: ${oc.env:PROJECT_ROOT}/data/ohlc_KO_PEP_NVDA_KSU_train.csv
      target_feature_price: ${nn.target_feature_price}
      target_feature_volume: ${nn.target_feature_volume}
      stock_names: ${nn.stock_names}
      encoder_length: 390
      decoder_length: 150
      stride: 1


    val:
      - _target_: thesis_gan.data.dataset.StockDataset
        path: ${oc.env:PROJECT_ROOT}/data/ohlc_KO_PEP_NVDA_KSU_val.csv
        target_feature_price: ${nn.target_feature_price}
        target_feature_volume: ${nn.target_feature_volume}
        stock_names: ${nn.stock_names}
        encoder_length: 390
        decoder_length: 150
        stride: 1

    test:
      - _target_: thesis_gan.data.dataset.StockDataset
        path: ${oc.env:PROJECT_ROOT}/data/ohlc_KO_PEP_NVDA_KSU_test.csv
        target_feature_price: ${nn.target_feature_price}
        target_feature_volume: ${nn.target_feature_volume}
        stock_names: ${nn.stock_names}
        encoder_length: 390
        decoder_length: 150
        stride: 1

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 12
    val: 12
    test: 12

  batch_size:
    train: 128
    val: 128
    test: 128

module:
  _target_: thesis_gan.pl_modules.pl_module.MyLightningModule

  dataset_type: ${nn.dataset_type}

  optimizer_g:
    _target_: torch.optim.RMSprop
    lr: 1e-4

  optimizer_d:
    _target_: torch.optim.RMSprop
    lr: 3e-4

  generator:
    _target_: thesis_gan.modules.generator.tcn.TCNGenerator
    encoder_length: ${nn.encoder_length}
    decoder_length: ${nn.decoder_length}
    hidden_dim: 256
    dropout: 0.2

  discriminator:
    _target_: thesis_gan.modules.discriminator.cnn.CNNDiscriminator
    encoder_length: ${nn.encoder_length}
    decoder_length: ${nn.decoder_length}
    hidden_dim: 256
    dropout: 0.2
    compute_corr: True

  stock_names: ${nn.stock_names}
  encoder_length: ${nn.encoder_length}
  decoder_length: ${nn.decoder_length}
  n_critic: 5
  val_log_freq: 5
