dataset_type: "multistock"
stock_names: [KO, PEP, NVDA, KSU]
#stock_names: [AAPL, AMGN, AXP, BA, CAT, CRM, CSCO, CVX, DIS, GS, HD, HON, IBM, INTC, JNJ, JPM, KO, MCD, MMM, MRK, MSFT, NKE, PG, TRV, UNH, V, VZ, WBA, WMT]

target_feature_price: mid_price
target_feature_volume: volume

encoder_length: 390
decoder_length: 150


data:
  _target_: thesis_gan.data.datamodule.MyDataModule

  dataset_type: ${nn.dataset_type}

  data_pipeline_price:
    _target_: thesis_gan.data.pipeline.LogReturnPipeline
    scaler:
      _target_: sklearn.preprocessing.StandardScaler

  data_pipeline_volume:
    _target_: thesis_gan.data.pipeline.ScalerPipeline
    scaler:
      _target_: sklearn.preprocessing.MinMaxScaler
      feature_range: ${as_tuple:-1,1} #[-1, 1]
    round: True
    log: True

  datasets:
    train:
      _target_: thesis_gan.data.dataset_train.StockDatasetTrain
      path: ${oc.env:PROJECT_ROOT}/data/ohlc_KO_PEP_NVDA_KSU_train.csv
      # path: ${oc.env:PROJECT_ROOT}/data/ohlc_DowJones/ohlc_DowJones_train.csv
      target_feature_price: ${nn.target_feature_price}
      target_feature_volume: ${nn.target_feature_volume}
      stock_names: ${nn.stock_names}
      encoder_length: 390
      decoder_length: 150
      stride: 1

    val:
      - _target_: thesis_gan.data.dataset_inference.StockDatasetInference
        path: ${oc.env:PROJECT_ROOT}/data/ohlc_KO_PEP_NVDA_KSU_val.csv
        # path: ${oc.env:PROJECT_ROOT}/data/ohlc_DowJones/ohlc_DowJones_val.csv
        target_feature_price: ${nn.target_feature_price}
        target_feature_volume: ${nn.target_feature_volume}
        stock_names: ${nn.stock_names}
        encoder_length: 390
        decoder_length: 150
        stride:

    test:
      - _target_: thesis_gan.data.dataset_inference.StockDatasetInference
        path: ${oc.env:PROJECT_ROOT}/data/ohlc_KO_PEP_NVDA_KSU_test.csv
        # path: ${oc.env:PROJECT_ROOT}/data/ohlc_DowJones/ohlc_DowJones_test.csv
        target_feature_price: ${nn.target_feature_price}
        target_feature_volume: ${nn.target_feature_volume}
        stock_names: ${nn.stock_names}
        encoder_length: 390
        decoder_length: 150
        stride:

  gpus: ${train.trainer.gpus}

  num_workers:
    train: 12
    val: 12
    test: 12

  batch_size:
    train: 128
    val: 1
    test: 1

module:
  _target_: thesis_gan.pl_modules.pl_module_conv.MyLightningModule

  dataset_type: ${nn.dataset_type}
  step_to_skip: 0
  model: 'conv'

  optimizer_g:
    _target_: torch.optim.RMSprop
    lr: 1e-4

  optimizer_d:
    _target_: torch.optim.RMSprop
    lr: 3e-4

  generator:
    #_target_: thesis_gan.modules.generator.rnn.RNNGenerator
    _target_: thesis_gan.modules.generator.tcn.TCNGenerator
    encoder_length: ${nn.encoder_length}
    decoder_length: ${nn.decoder_length}
    hidden_dim: 256
    dropout: 0.2

  discriminator:
    _target_: thesis_gan.modules.discriminator.cnn.CNNDiscriminator
    encoder_length: ${nn.encoder_length}
    decoder_length: ${nn.decoder_length}
    hidden_dim: 256
    dropout: 0.2
    compute_corr: True
    alpha:

  target_feature_price: ${nn.target_feature_price}
  target_feature_volume: ${nn.target_feature_volume}
  stock_names: ${nn.stock_names}
  encoder_length: ${nn.encoder_length}
  decoder_length: ${nn.decoder_length}
  n_critic: 5
  val_log_freq: 5
  delta: 15
  save_reals: True
