_target_: lightning.pytorch.Trainer
fast_dev_run: False
detect_anomaly: ${trainer.fast_dev_run}
max_epochs: 300
accumulate_grad_batches: 1
num_sanity_val_steps: 2
val_check_interval: 1.0
# gradient_clip_val: 10.0
# precision: 32
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${path_checkpoint}
    filename: 'epoch={epoch:02d}-loss_g={loss/generator:.3f}'
    monitor: 'loss/generator'
    save_top_k: -1
    mode: 'min'
    auto_insert_metric_name: False
