_target_: lightning.pytorch.Trainer
fast_dev_run: True
detect_anomaly: ${trainer.fast_dev_run}
inference_mode: False
max_epochs: 100
callbacks:
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ${path_checkpoint}
    filename: 'epoch={epoch:02d}-val={val/loss:.3f}'
    monitor: val/loss
    save_top_k: 3
    mode: 'min'
    auto_insert_metric_name: False
  # - _target_: lightning.pytorch.callbacks.EarlyStopping
  #   monitor: val/f1
  #   patience: 3
  #   mode: 'max'
  #   min_delta: 0.001