seed: 42

encoder_length: 390
decoder_length: 150
batch_size: 128

defaults:
  - dataset: multistock
  - datamodule: default
  - model: default
  - logger: default
  - trainer: default
  - hydra: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_
