seed: 42

ckpt_path: # storage/9l5lbw8e/checkpoints/epoch=176.ckpt

encoder_length: 390
decoder_length: 150
generation_length: 8969
batch_size: 128

defaults:
  - dataset: multistock
  - datamodule: default
  - model: default
  - logger: default
  - trainer: default
  - hydra: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_
