seed: 42

seq_len: 150

batch_size: 16
lr: .001

ckpt_path: # storage/vb7m8jvt/checkpoints/epoch=05-val_f1=0.399.ckpt

defaults:
  - model: csdi
  - dataset: stocks
  - pl_model: default
  - datamodule: default
  - logger: default
  - trainer: default
  - hydra: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_
